### ISSUE TITLE
Wrap IOExceptions in NodeError more readable

### ISSUE THREAD

**Issue by msmolyakov** [msmolyakov/paddle#22]
In the error below most important part is just `"Error while executing account-script: value() called on unit value"`:
```
im.mak.paddle.exceptions.NodeError: java.io.IOException: {"trace":[{"dApp":"3MDFNde2fvqJUEY5BFymeztBuwGRSnWwXC8","function":"buyBack","args":[],"error":{"type":"Account","vars":[{"name":"i","value":"Invocation(\n\tcallerPublicKey = base58'BcX4dweiGXRvsqvUKQLGx4wt1zYqp3nFLtfweEWmeU27'\n\tfeeAssetId = Unit\n\tpayment = AttachedPayment(\n\t\tamount = 200000000000\n\t\tassetId = Unit\n\t)\n\ttransactionId = base58'2YYuYkUaM7WNxHAbgwCqnn2VvAfqAQbucBEEDwmSYAqM'\n\tcaller = Address(\n\t\tbytes = base58'3M7iCjnZZ7akRqH8RwXxPwkNPYfoHi38BfE'\n\t)\n\tfee = 500000\n)"},{"name":"@a","value":"AttachedPayment(\n\tamount = 200000000000\n\tassetId = Unit\n)"},{"name":"@a","value":"Unit"}],"reason":"value() called on unit value"}}],"error":306,"message":"Error while executing account-script: value() called on unit value","transaction":{"senderPublicKey":"BcX4dweiGXRvsqvUKQLGx4wt1zYqp3nFLtfweEWmeU27","call":{"function":"buyBack","args":[]},"dApp":"3MDFNde2fvqJUEY5BFymeztBuwGRSnWwXC8","sender":"3M7iCjnZZ7akRqH8RwXxPwkNPYfoHi38BfE","feeAssetId":null,"proofs":["2CGSU7QpMNgPsKB6oSu8kBdVfw2i1g5iydBrhUbvZjdiBPYaw8eRXnUmpadGPrVTF79nuyqhHEk476cBLSovLLoZ"],"fee":500000,"payment":[{"amount":200000000000,"assetId":null}],"id":"2YYuYkUaM7WNxHAbgwCqnn2VvAfqAQbucBEEDwmSYAqM","type":16,"version":1,"timestamp":1565105322069}}

	at im.mak.paddle.Node.send(Node.java:331)
	at im.mak.paddle.Account.invokes(Account.java:203)
	at paddle.UpdateRateTest.bobCanBuybackAfterGrace(UpdateRateTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:628)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:117)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:184)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:180)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:127)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.io.IOException: {"trace":[{"dApp":"3MDFNde2fvqJUEY5BFymeztBuwGRSnWwXC8","function":"buyBack","args":[],"error":{"type":"Account","vars":[{"name":"i","value":"Invocation(\n\tcallerPublicKey = base58'BcX4dweiGXRvsqvUKQLGx4wt1zYqp3nFLtfweEWmeU27'\n\tfeeAssetId = Unit\n\tpayment = AttachedPayment(\n\t\tamount = 200000000000\n\t\tassetId = Unit\n\t)\n\ttransactionId = base58'2YYuYkUaM7WNxHAbgwCqnn2VvAfqAQbucBEEDwmSYAqM'\n\tcaller = Address(\n\t\tbytes = base58'3M7iCjnZZ7akRqH8RwXxPwkNPYfoHi38BfE'\n\t)\n\tfee = 500000\n)"},{"name":"@a","value":"AttachedPayment(\n\tamount = 200000000000\n\tassetId = Unit\n)"},{"name":"@a","value":"Unit"}],"reason":"value() called on unit value"}}],"error":306,"message":"Error while executing account-script: value() called on unit value","transaction":{"senderPublicKey":"BcX4dweiGXRvsqvUKQLGx4wt1zYqp3nFLtfweEWmeU27","call":{"function":"buyBack","args":[]},"dApp":"3MDFNde2fvqJUEY5BFymeztBuwGRSnWwXC8","sender":"3M7iCjnZZ7akRqH8RwXxPwkNPYfoHi38BfE","feeAssetId":null,"proofs":["2CGSU7QpMNgPsKB6oSu8kBdVfw2i1g5iydBrhUbvZjdiBPYaw8eRXnUmpadGPrVTF79nuyqhHEk476cBLSovLLoZ"],"fee":500000,"payment":[{"amount":200000000000,"assetId":null}],"id":"2YYuYkUaM7WNxHAbgwCqnn2VvAfqAQbucBEEDwmSYAqM","type":16,"version":1,"timestamp":1565105322069}}
	at com.wavesplatform.wavesj.Node.exec(Node.java:602)
	at com.wavesplatform.wavesj.Node.send(Node.java:308)
	at com.wavesplatform.wavesj.Node.invokeScript(Node.java:370)
	at im.mak.paddle.Node.send(Node.java:327)
	... 53 more
```

**Comment by msmolyakov** [comment]
done since 1.0.0-rc1
